### ISSUE TITLE
train_bert_gcn.py中是否会发生数据泄露

### ISSUE THREAD

**Issue by Im-not-shuo** [ZeroRin/BertGCN#15]
训练所用的idx_loader是由doc_idx得到，doc_idx是将train_idx, val_idx, test_idx合起来得到。想问一下这样是否会造成数据泄露

**Comment by ZeroRin** [comment]
training过程中仅使用到了val和test集的数据，而没有使用其标签信息。这一模式与TextGCN一线的工作是保持一致的，我认为不算数据泄露。

**Comment by Im-not-shuo** [comment]
> training过程中仅使用到了val和test集的数据，而没有使用其标签信息。这一模式与TextGCN一线的工作是保持一致的，我认为不算数据泄露。

好的，谢谢
