### ISSUE TITLE
请问，在跑自己数据集，训练时，前几个epoch出现一个test acc很高的值（第14个），然而后面的epoch的acc很低，这是什么原因呢？

### ISSUE THREAD

**Issue by Jungle-liu** [ZeroRin/BertGCN#5]
Epoch: 1  Train acc: 0.5904 loss: 0.6174  Val acc: 0.5828 loss: 0.6347  Test acc: 0.5469 loss: 0.7232
New checkpoint
Epoch: 2  Train acc: 0.5018 loss: 0.7964  Val acc: 0.5045 loss: 0.7927  Test acc: 0.5044 loss: 0.7967
Epoch: 3  Train acc: 0.6035 loss: 0.6463  Val acc: 0.5923 loss: 0.6950  Test acc: 0.6178 loss: 0.7489
New checkpoint
Epoch: 4  Train acc: 0.5031 loss: 0.7293  Val acc: 0.4991 loss: 0.7661  Test acc: 0.5031 loss: 0.8364
Epoch: 5  Train acc: 0.5006 loss: 0.7919  Val acc: 0.4973 loss: 0.8167  Test acc: 0.5010 loss: 0.8850
Epoch: 6  Train acc: 0.5021 loss: 0.6507  Val acc: 0.4991 loss: 0.6769  Test acc: 0.5029 loss: 0.6873
Epoch: 7  Train acc: 0.5299 loss: 0.6656  Val acc: 0.5272 loss: 0.6932  Test acc: 0.5445 loss: 0.6999
Epoch: 8  Train acc: 0.5003 loss: 1.0031  Val acc: 0.4973 loss: 0.9910  Test acc: 0.5000 loss: 1.0739
Epoch: 9  Train acc: 0.5003 loss: 0.6611  Val acc: 0.4973 loss: 0.7451  Test acc: 0.5000 loss: 0.7582
Epoch: 10  Train acc: 0.5003 loss: 0.6498  Val acc: 0.4973 loss: 0.6794  Test acc: 0.5000 loss: 0.6771
Epoch: 11  Train acc: 0.5003 loss: 0.8106  Val acc: 0.4973 loss: 1.0257  Test acc: 0.5000 loss: 1.1180
Epoch: 12  Train acc: 0.5003 loss: 0.6220  Val acc: 0.4973 loss: 0.7097  Test acc: 0.5000 loss: 0.7125
Epoch: 13  Train acc: 0.5003 loss: 0.6249  Val acc: 0.4973 loss: 0.7085  Test acc: 0.5000 loss: 0.6998
Epoch: 14  Train acc: 0.7945 loss: 0.3796  Val acc: 0.7621 loss: 0.5007  Test acc: 0.7028 loss: 0.6082
New checkpoint
Epoch: 15  Train acc: 0.5800 loss: 0.6389  Val acc: 0.5750 loss: 0.7032  Test acc: 0.5825 loss: 0.7746
Epoch: 16  Train acc: 0.5064 loss: 0.7587  Val acc: 0.5039 loss: 0.8352  Test acc: 0.5067 loss: 0.9176
Epoch: 17  Train acc: 0.5432 loss: 0.6097  Val acc: 0.5368 loss: 0.6716  Test acc: 0.5846 loss: 0.6236
Epoch: 18  Train acc: 0.5675 loss: 0.7274  Val acc: 0.5523 loss: 0.8479  Test acc: 0.5462 loss: 0.9397
Epoch: 19  Train acc: 0.4997 loss: 0.7811  Val acc: 0.5027 loss: 0.7785  Test acc: 0.5000 loss: 0.7809
Epoch: 20  Train acc: 0.4997 loss: 0.7807  Val acc: 0.5027 loss: 0.7781  Test acc: 0.5000 loss: 0.7804
Epoch: 21  Train acc: 0.4997 loss: 0.7806  Val acc: 0.5027 loss: 0.7781  Test acc: 0.5000 loss: 0.7804
Epoch: 22  Train acc: 0.4997 loss: 0.7806  Val acc: 0.5027 loss: 0.7781  Test acc: 0.5000 loss: 0.7803
Epoch: 23  Train acc: 0.4997 loss: 0.7806  Val acc: 0.5027 loss: 0.7780  Test acc: 0.5000 loss: 0.7803
Epoch: 24  Train acc: 0.4997 loss: 0.7806  Val acc: 0.5027 loss: 0.7780  Test acc: 0.5000 loss: 0.7803
Epoch: 25  Train acc: 0.4997 loss: 0.7806  Val acc: 0.5027 loss: 0.7780  Test acc: 0.5000 loss: 0.7803
Epoch: 26  Train acc: 0.4997 loss: 0.7806  Val acc: 0.5027 loss: 0.7780  Test acc: 0.5000 loss: 0.7803
Epoch: 27  Train acc: 0.4997 loss: 0.7806  Val acc: 0.5027 loss: 0.7780  Test acc: 0.5000 loss: 0.7803
Epoch: 28  Train acc: 0.4997 loss: 0.7806  Val acc: 0.5027 loss: 0.7780  Test acc: 0.5000 loss: 0.7803
Epoch: 29  Train acc: 0.4997 loss: 0.7806  Val acc: 0.5027 loss: 0.7780  Test acc: 0.5000 loss: 0.7803
Epoch: 30  Train acc: 0.4997 loss: 0.7806  Val acc: 0.5027 loss: 0.7780  Test acc: 0.5000 loss: 0.7803
Epoch: 31  Train acc: 0.4997 loss: 0.7806  Val acc: 0.5027 loss: 0.7780  Test acc: 0.5000 loss: 0.7803
Epoch: 32  Train acc: 0.4997 loss: 0.7806  Val acc: 0.5027 loss: 0.7780  Test acc: 0.5000 loss: 0.7803
Epoch: 33  Train acc: 0.4997 loss: 0.7806  Val acc: 0.5027 loss: 0.7780  Test acc: 0.5000 loss: 0.7803
Epoch: 34  Train acc: 0.4997 loss: 0.7806  Val acc: 0.5027 loss: 0.7780  Test acc: 0.5000 loss: 0.7803
Epoch: 35  Train acc: 0.4997 loss: 0.7806  Val acc: 0.5027 loss: 0.7780  Test acc: 0.5000 loss: 0.7803
Epoch: 36  Train acc: 0.4997 loss: 0.7806  Val acc: 0.5027 loss: 0.7780  Test acc: 0.5000 loss: 0.7803
Epoch: 37  Train acc: 0.4997 loss: 0.7806  Val acc: 0.5027 loss: 0.7780  Test acc: 0.5000 loss: 0.7803
Epoch: 38  Train acc: 0.4997 loss: 0.7806  Val acc: 0.5027 loss: 0.7780  Test acc: 0.5000 loss: 0.7803
Epoch: 39  Train acc: 0.4997 loss: 0.7806  Val acc: 0.5027 loss: 0.7780  Test acc: 0.5000 loss: 0.7803
Epoch: 40  Train acc: 0.4997 loss: 0.7806  Val acc: 0.5027 loss: 0.7780  Test acc: 0.5000 loss: 0.7803
Epoch: 41  Train acc: 0.4997 loss: 0.7806  Val acc: 0.5027 loss: 0.7780  Test acc: 0.5000 loss: 0.7803
Epoch: 42  Train acc: 0.4997 loss: 0.7806  Val acc: 0.5027 loss: 0.7780  Test acc: 0.5000 loss: 0.7803
Epoch: 43  Train acc: 0.4997 loss: 0.7806  Val acc: 0.5027 loss: 0.7780  Test acc: 0.5000 loss: 0.7803
Epoch: 44  Train acc: 0.4997 loss: 0.7806  Val acc: 0.5027 loss: 0.7780  Test acc: 0.5000 loss: 0.7803
Epoch: 45  Train acc: 0.4997 loss: 0.7806  Val acc: 0.5027 loss: 0.7780  Test acc: 0.5000 loss: 0.7803
Epoch: 46  Train acc: 0.4997 loss: 0.7806  Val acc: 0.5027 loss: 0.7780  Test acc: 0.5000 loss: 0.7803
Epoch: 47  Train acc: 0.4997 loss: 0.7806  Val acc: 0.5027 loss: 0.7780  Test acc: 0.5000 loss: 0.7803
Epoch: 48  Train acc: 0.4997 loss: 0.7806  Val acc: 0.5027 loss: 0.7780  Test acc: 0.5000 loss: 0.7803
Epoch: 49  Train acc: 0.4997 loss: 0.7806  Val acc: 0.5027 loss: 0.7780  Test acc: 0.5000 loss: 0.7803
Epoch: 50  Train acc: 0.4997 loss: 0.7806  Val acc: 0.5027 loss: 0.7780  Test acc: 0.5000 loss: 0.7803

**Comment by ZeroRin** [comment]
不太想得到原因，但这个整体走势就是完全训练不动吧。。只用bert能训练到收敛吗？
